username: sdhruv@ucsd.edu
password: random902
phone_number: 8018150123

positions:
- Software Engineer
- Molding Engineer
- DevOps Engineer
- Software Development Engineer
- Backend Software Engineer
- Full Stack Software Engineer
- Frontend Software Engineer
- Embedded Software Engineer
- Machine Learning Engineer
- Process Engineer
- Manufacturing Engineer
- Injection Engineer
- Tooling Engineer
- Plastics Engineer
- Production Engineer
- Senior Engineer
- Design Engineer
- Automation Engineer
- Project Engineer


locations:
- Remote
- Los Angeles 

# --------- Optional Parameters -------
# uploads:
#  Resume: # PATH TO Resume 
#  Cover Letter: # PATH TO cover letter
#  Photo: # PATH TO photo


# output_filename:
# - # PATH TO OUTPUT FILE (default output.csv)

# blacklist:
# - # Jobot
# - # CyberCoders

#blackListTitles:
#- # Add job titles you want to ignore
